---
name: "gps"
version: "1.0.10"
description: Serial GPS receiver
url: https://github.com/iot49/HA-addons/gps
slug: "gps"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: debug
  homeassistant_api: true
  usb: true
  uart: true
  # how access usb without this?
  devices:
    - "/dev/USB0"
  full_access: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
init: false
