---
name: "gps"
version: "1.0.13"
description: Serial GPS receiver
url: https://github.com/iot49/HA-addons/gps
slug: "gps"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: debug
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
init: false
uart: true
# hassio_api: true
# hassio_role: manager
homeassistant_api: true
