---
name: "RV-C"
version: "1.0.6"
description: RV-C Interface
url: https://github.com/iot49/HA-addons
slug: "rv_c"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)

